[package]
name = "common"
version = "0.1.0"
edition = "2021"

[dependencies]
bytemuck = { version = "1.14.0", features = ["derive", "min_const_generics", "extern_crate_alloc"] }
itertools = "0.13.0"
spin = "0.9.8"
thread_local = "1.1.8"
paste = "1.0.15"
