[package]
name = "partitioned-aggregate"
version = "0.1.0"
edition = "2024"

[dependencies]
thread_local = "1.1.8"
fnv = "1.0.7"
itertools = "0.14.0"
hashbrown = "0.15.3"
bytemuck = { version = "1.23.1", features = ["extern_crate_alloc"] }

[dev-dependencies]
fastrand = "2.1"
